const state={data:null,selected:null,deferred:null};
const $=s=>document.querySelector(s);
const base=()=>state.data?.mediaBase||"";
function media(path){return path?base()+path:""}
function card(item,kind){const el=document.createElement("article");el.className="card";const title=item.title||item.label||item.name;el.innerHTML=`<h3>${title}</h3><small>${item.duration||item.description||""}</small>`;const actions=document.createElement("div");actions.className="card-actions";if(item.video){const b=document.createElement("button");b.className="primary";b.textContent="Play video";b.onclick=()=>select(item);actions.append(b)}if(item.audio){const b=document.createElement("button");b.textContent="Audio only";b.onclick=()=>select(item,true);actions.append(b)}if(item.video){const a=document.createElement("a");a.textContent="Download video";a.href=media(item.video);a.download="";actions.append(a)}if(item.audio){const a=document.createElement("a");a.textContent="Download audio";a.href=media(item.audio);a.download="";actions.append(a)}el.append(actions);return el}
function render(){const d=state.data;$("#song-count").textContent=d.songs.length;$("#video-count").textContent=d.songs.filter(x=>x.video).length+(d.fullVideo?1:0);const songs=$("#songs");songs.replaceChildren(...d.songs.map(x=>card(x,"song")));const hi=$("#highlights");hi.replaceChildren(...(d.highlights||[]).map(x=>card(x,"highlight")));const full=$("#full");full.replaceChildren(card({title:"Full Sonidos set",description:"Album-order video",video:d.fullVideo,audio:d.fullAudio},"full"));}
function select(item,audioOnly=false){state.selected=item;$("#now").textContent=item.title||item.name||item.label;$("#now-meta").textContent=item.duration||"Full set";const v=$("#video"),a=$("#audio");v.pause();a.pause();v.src=item.video?media(item.video):"";a.src=item.audio?media(item.audio):"";if(audioOnly){v.removeAttribute("src");a.play().catch(()=>{})}else if(item.video){v.play().catch(()=>{})}window.scrollTo({top:0,behavior:"smooth"})}
document.querySelectorAll(".tab").forEach(tab=>tab.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.setAttribute("aria-selected",x===tab));["songs","highlights","full"].forEach(v=>document.getElementById(`${v}-view`).hidden=tab.dataset.view!==v)});
window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();state.deferred=e;$("#install").hidden=false});$("#install").onclick=async()=>{if(state.deferred){state.deferred.prompt();await state.deferred.userChoice;state.deferred=null;$("#install").hidden=true}};
fetch("./data.json").then(r=>r.json()).then(d=>{state.data=d;render();if("serviceWorker" in navigator)navigator.serviceWorker.register("./sw.js",{scope:"./"})}).catch(()=>{$("#songs").textContent="The delivery manifest is offline. Reconnect to load the media."});
