window.SONIDOS_CATALOG = {
  "title": "Sonidos 2025",
  "mediaBase": "https://renatodap.me/s3/sonidos-2025/",
  "songs": [
    {
      "number": 1,
      "label": "warpigs",
      "title": "War Pigs",
      "duration": 468.06204081632654,
      "video": "songs/01-warpigs.mp4",
      "audio": "audio/01-warpigs.m4a?v=cbab33edd419",
      "master": "audio/01-warpigs.wav?v=7c9d83d5e8b6",
      "thumbnail": "./thumbnails/01-warpigs-16x9.webp",
      "artist": "Black Sabbath",
      "thumbnailFallback": "./thumbs/01-warpigs.jpg",
      "artwork": "./thumbnails/01-warpigs-square.webp",
      "artworkReady": false,
      "audioReady": true,
      "videoReady": true,
      "masterReady": true,
      "youtubeId": "CuVkTWLp6Bs"
    },
    {
      "number": 2,
      "label": "alive",
      "title": "Alive",
      "duration": 302.02083900226756,
      "video": "songs/02-alive.mp4",
      "audio": "audio/02-alive.m4a?v=e4f0fb8c5739",
      "master": "audio/02-alive.wav?v=c6f5ba21b413",
      "thumbnail": "./thumbnails/02-alive-16x9.webp",
      "artist": "Pearl Jam",
      "thumbnailFallback": "./thumbs/02-alive.jpg",
      "artwork": "./thumbnails/02-alive-square.webp",
      "artworkReady": true,
      "audioReady": true,
      "videoReady": false,
      "masterReady": true
    },
    {
      "number": 3,
      "label": "belltolls",
      "title": "For Whom the Bell Tolls",
      "duration": 292.0751020408163,
      "video": "songs/03-belltolls.mp4",
      "audio": "audio/03-belltolls.m4a?v=f10e0773e69d",
      "master": "audio/03-belltolls.wav?v=bf69d2ffa0c1",
      "thumbnail": "./thumbnails/03-belltolls-16x9.webp",
      "artist": "Metallica",
      "thumbnailFallback": "./thumbs/03-belltolls.jpg",
      "artwork": "./thumbnails/03-belltolls-square.webp",
      "artworkReady": false,
      "audioReady": true,
      "videoReady": false,
      "masterReady": true
    },
    {
      "number": 4,
      "label": "numb",
      "title": "Comfortably Numb",
      "duration": 600.0587755102041,
      "video": "songs/04-numb.mp4",
      "audio": "audio/04-numb.m4a?v=d2393fc34404",
      "master": "audio/04-numb.wav?v=dfa406e518d4",
      "thumbnail": "./thumbnails/04-numb-16x9.webp",
      "artist": "Pink Floyd",
      "thumbnailFallback": "./thumbs/04-numb.jpg",
      "artwork": "./thumbnails/04-numb-square.webp",
      "artworkReady": false,
      "audioReady": true,
      "videoReady": false,
      "masterReady": true
    },
    {
      "number": 5,
      "label": "wishhere",
      "title": "Wish You Were Here",
      "duration": 311.0660997732426,
      "video": "songs/05-wishhere.mp4",
      "audio": "audio/05-wishhere.m4a?v=c2a5e8ad629e",
      "master": "audio/05-wishhere.wav?v=3d1f5101cf7f",
      "thumbnail": "./thumbnails/05-wishhere-16x9.webp",
      "artist": "Pink Floyd",
      "thumbnailFallback": "./thumbs/05-wishhere.jpg",
      "artwork": "./thumbnails/05-wishhere-square.webp",
      "artworkReady": false,
      "audioReady": true,
      "videoReady": true,
      "masterReady": true,
      "youtubeId": "IB8TieRb03A"
    },
    {
      "number": 6,
      "label": "time",
      "title": "Time",
      "duration": 364.5444671201814,
      "video": "songs/06-time.mp4",
      "audio": "audio/06-time.m4a?v=a767eaf5245c",
      "master": "audio/06-time.wav?v=47f20237d02b",
      "thumbnail": "./thumbnails/06-time-16x9.webp",
      "artist": "Pink Floyd",
      "thumbnailFallback": "./thumbs/06-time.jpg",
      "artwork": "./thumbnails/06-time-square.webp",
      "artworkReady": false,
      "audioReady": true,
      "videoReady": false,
      "masterReady": true
    },
    {
      "number": 7,
      "label": "mania",
      "title": "Mania de Você",
      "duration": 440.0604081632653,
      "video": "songs/07-mania.mp4",
      "audio": "audio/07-mania.m4a?v=d2156326ec4b",
      "master": "audio/07-mania.wav?v=3d1cf7f224fa",
      "thumbnail": "./thumbnails/07-mania-16x9.webp",
      "artist": "Rita Lee",
      "thumbnailFallback": "./thumbs/07-mania.jpg",
      "artwork": "./thumbnails/07-mania-square.webp",
      "artworkReady": false,
      "audioReady": true,
      "videoReady": false,
      "masterReady": true
    },
    {
      "number": 8,
      "label": "descobridor",
      "title": "O Descobridor",
      "duration": 350.0669387755102,
      "video": "songs/08-descobridor.mp4",
      "audio": "audio/08-descobridor.m4a?v=1fb0788ce8bb",
      "master": "audio/08-descobridor.wav?v=a801a2ca7ff9",
      "thumbnail": "./thumbnails/08-descobridor-16x9.webp",
      "artist": "Tim Maia",
      "thumbnailFallback": "./thumbs/08-descobridor.jpg",
      "artwork": "./thumbnails/08-descobridor-square.webp",
      "artworkReady": false,
      "audioReady": true,
      "videoReady": false,
      "masterReady": true
    },
    {
      "number": 9,
      "label": "hotelcalifornia",
      "title": "Hotel California",
      "duration": 472.96777777777777,
      "video": "songs/09-hotelcalifornia.mp4",
      "audio": "audio/09-hotelcalifornia.m4a?v=657b66b1d96c",
      "master": "audio/09-hotelcalifornia.wav",
      "thumbnail": "./thumbnails/09-hotelcalifornia-16x9.webp",
      "artist": "Eagles",
      "thumbnailFallback": "./thumbs/09-hotelcalifornia.jpg",
      "artwork": "./thumbnails/09-hotelcalifornia-square.webp",
      "artworkReady": false,
      "audioReady": true,
      "videoReady": false,
      "masterReady": false
    },
    {
      "number": 10,
      "label": "cantstop",
      "title": "Can't Stop",
      "duration": 322.06367346938777,
      "video": "songs/10-cantstop.mp4",
      "audio": "audio/10-cantstop.m4a?v=68ebdd26edf9",
      "master": "audio/10-cantstop.wav?v=6d9e8f3ba5c7",
      "thumbnail": "./thumbnails/10-cantstop-16x9.webp",
      "artist": "Red Hot Chili Peppers",
      "thumbnailFallback": "./thumbs/10-cantstop.jpg",
      "artwork": "./thumbnails/10-cantstop-square.webp",
      "artworkReady": false,
      "audioReady": true,
      "videoReady": false,
      "masterReady": true
    },
    {
      "number": 11,
      "label": "bridge",
      "title": "Under the Bridge",
      "duration": 273.5959637188209,
      "video": "songs/11-bridge.mp4",
      "audio": "audio/11-bridge.m4a?v=d85a0aa6979e",
      "master": "audio/11-bridge.wav",
      "thumbnail": "./thumbnails/11-bridge-16x9.webp",
      "artist": "Red Hot Chili Peppers",
      "thumbnailFallback": "./thumbs/11-bridge.jpg",
      "artwork": "./thumbnails/11-bridge-square.webp",
      "artworkReady": false,
      "audioReady": true,
      "videoReady": true,
      "masterReady": false,
      "youtubeId": "QP-KnDjYqbk"
    },
    {
      "number": 12,
      "label": "everybody",
      "title": "Everybody Wants to Rule the World",
      "duration": 288.0522222222222,
      "video": "songs/12-everybody.mp4",
      "audio": "audio/12-everybody.m4a?v=a559d2388d8a",
      "master": "audio/12-everybody.wav",
      "thumbnail": "./thumbnails/12-everybody-16x9.webp",
      "artist": "Tears for Fears",
      "thumbnailFallback": "./thumbs/12-everybody.jpg",
      "artwork": "./thumbnails/12-everybody-square.webp",
      "artworkReady": false,
      "audioReady": true,
      "videoReady": true,
      "masterReady": false,
      "youtubeId": "Cqdv8zbQ8D8"
    },
    {
      "number": 13,
      "label": "everlong",
      "title": "Everlong",
      "duration": 281.4652607709751,
      "video": "songs/13-everlong.mp4",
      "audio": "audio/13-everlong.m4a?v=06d95588625e",
      "master": "audio/13-everlong.wav",
      "thumbnail": "./thumbnails/13-everlong-16x9.webp",
      "artist": "Foo Fighters",
      "thumbnailFallback": "./thumbs/13-everlong.jpg",
      "artwork": "./thumbnails/13-everlong-square.webp",
      "artworkReady": false,
      "audioReady": true,
      "videoReady": false,
      "masterReady": false
    },
    {
      "number": 14,
      "label": "aerials",
      "title": "Aerials",
      "duration": 314.07020408163265,
      "video": "songs/14-aerials.mp4",
      "audio": "audio/14-aerials.m4a?v=30a974add8ed",
      "master": "audio/14-aerials.wav",
      "thumbnail": "./thumbnails/14-aerials-16x9.webp",
      "artist": "System of a Down",
      "thumbnailFallback": "./thumbs/14-aerials.jpg",
      "artwork": "./thumbnails/14-aerials-square.webp",
      "artworkReady": false,
      "audioReady": true,
      "videoReady": false,
      "masterReady": false
    },
    {
      "number": 15,
      "label": "evenflow",
      "title": "Even Flow",
      "duration": 280.0587755102041,
      "video": "songs/15-evenflow.mp4",
      "audio": "audio/15-evenflow.m4a?v=683da6bbdb55",
      "master": "audio/15-evenflow.wav",
      "thumbnail": "./thumbnails/15-evenflow-16x9.webp",
      "artist": "Pearl Jam",
      "thumbnailFallback": "./thumbs/15-evenflow.jpg",
      "artwork": "./thumbnails/15-evenflow-square.webp",
      "artworkReady": false,
      "audioReady": true,
      "videoReady": false,
      "masterReady": false
    },
    {
      "number": 16,
      "label": "chain",
      "title": "The Chain",
      "duration": 346.0704081632653,
      "video": "songs/16-chain.mp4",
      "audio": "audio/16-chain.m4a?v=d5fe0e6b3577",
      "master": "audio/16-chain.wav",
      "thumbnail": "./thumbnails/16-chain-16x9.webp",
      "artist": "Fleetwood Mac",
      "thumbnailFallback": "./thumbs/16-chain.jpg",
      "artwork": "./thumbnails/16-chain-square.webp",
      "artworkReady": false,
      "audioReady": true,
      "videoReady": false,
      "masterReady": false
    },
    {
      "number": 17,
      "label": "dreams",
      "title": "Dreams",
      "duration": 392.0718367346939,
      "video": "songs/17-dreams.mp4",
      "audio": "audio/17-dreams.m4a?v=cd988ad6f3a6",
      "master": "audio/17-dreams.wav",
      "thumbnail": "./thumbnails/17-dreams-16x9.webp",
      "artist": "Fleetwood Mac",
      "thumbnailFallback": "./thumbs/17-dreams.jpg",
      "artwork": "./thumbnails/17-dreams-square.webp",
      "artworkReady": false,
      "audioReady": true,
      "videoReady": false,
      "masterReady": false
    },
    {
      "number": 18,
      "label": "creep",
      "title": "Creep",
      "duration": 287.0595918367347,
      "video": "songs/18-creep.mp4",
      "audio": "audio/18-creep.m4a?v=853a991d40e1",
      "master": "audio/18-creep.wav",
      "thumbnail": "./thumbnails/18-creep-16x9.webp",
      "artist": "Radiohead",
      "thumbnailFallback": "./thumbs/18-creep.jpg",
      "artwork": "./thumbnails/18-creep-square.webp",
      "artworkReady": false,
      "audioReady": true,
      "videoReady": false,
      "masterReady": false
    },
    {
      "number": 19,
      "label": "killing",
      "title": "Killing in the Name",
      "duration": 345.0775510204082,
      "video": "songs/19-killing.mp4",
      "audio": "audio/19-killing.m4a?v=38901ad22003",
      "master": "audio/19-killing.wav",
      "thumbnail": "./thumbnails/19-killing-16x9.webp",
      "artist": "Rage Against the Machine",
      "thumbnailFallback": "./thumbs/19-killing.jpg",
      "artwork": "./thumbnails/19-killing-square.webp",
      "artworkReady": false,
      "audioReady": true,
      "videoReady": false,
      "masterReady": false
    },
    {
      "number": 20,
      "label": "ironman",
      "title": "Iron Man",
      "duration": 398.57643990929705,
      "video": "songs/20-ironman.mp4",
      "audio": "audio/20-ironman.m4a?v=60041121f072",
      "master": "audio/20-ironman.wav",
      "thumbnail": "./thumbnails/20-ironman-16x9.webp",
      "artist": "Black Sabbath",
      "thumbnailFallback": "./thumbs/20-ironman.jpg",
      "artwork": "./thumbnails/20-ironman-square.webp",
      "artworkReady": false,
      "audioReady": true,
      "videoReady": false,
      "masterReady": false
    }
  ],
  "fullVideo": "full/FULL-Sonidos-Studio-Cuts.mp4",
  "fullAudio": "full/FULL-Sonidos-Studio-Cuts.m4a",
  "mediaReady": false,
  "audioReady": false,
  "fullMaster": "full/FULL-Sonidos-Studio-Cuts.wav",
  "fullDuration": 7129.0,
  "artist": "Caceta de Golira",
  "fullThumbnail": "./thumbnails/full-set-16x9.webp",
  "fullArtwork": "./thumbnails/full-set-square.webp",
  "artworkReady": false,
  "releaseVersion": "v1",
  "hidePending": true,
  "releasedAt": "2026-09-21T20:30:57Z",
  "fullVideoReady": false
};
