server {
    listen 3000;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location = /sonidos-2025 {
        return 308 /sonidos-2025/;
    }

    location /sonidos-2025/ {
        try_files $uri $uri/ /sonidos-2025/index.html;
    }
}
