import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
const base = (process.argv[2] || 'https://renatodap.me/sonidos-2025/').replace(/\/$/, '');
const browser = await chromium.launch();
const context = await browser.newContext({ viewport: { width: 390, height: 844 } });
const page = await context.newPage();
const errors=[]; page.on('pageerror', e=>errors.push(e.message));
try {
 await page.goto(base, {waitUntil:'networkidle'});
 assert.equal(new URL(page.url()).pathname,'/sonidos-2025/');
 assert.equal(await page.evaluate(()=>getComputedStyle(document.body).backgroundColor),'rgb(23, 23, 22)');
 const catalog=await page.evaluate(()=>window.SONIDOS_CATALOG);
 const published=catalog.songs.filter(s=>s.videoReady);
 assert.ok(published.length>=3);
 assert.equal(await page.locator('.video-card').count(),published.length);
 await page.getByRole('button',{name:'Play Under the Bridge',exact:true}).click();
 assert.match(await page.locator('#youtube').getAttribute('src'),/embed\/QP-KnDjYqbk/);
 await page.getByRole('button',{name:'Audio',exact:true}).click();
 assert.equal(await page.locator('.audio-row').count(),20+(catalog.fullAudioReady?1:0));
 assert.equal(await page.locator('.audio-row button.track-play:disabled').count(),0);
 await page.getByRole('button',{name:'Play Creep',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('#audio').currentTime>0,{},{timeout:30000});
 assert.equal(await page.evaluate(()=>navigator.mediaSession.metadata.title),'Creep');
 await page.evaluate(()=>document.querySelector('#audio').currentTime=90);
 await page.waitForFunction(()=>document.querySelector('#audio').currentTime>90,{},{timeout:15000});
 await page.getByRole('button',{name:'Save offline Creep',exact:true}).click();
 await page.getByRole('button',{name:'Remove offline copy of Creep',exact:true}).waitFor({timeout:90000});
 await page.getByRole('button',{name:'Close audio player',exact:true}).click();
 await page.evaluate(()=>navigator.serviceWorker.ready);
 await page.waitForFunction(()=>navigator.serviceWorker.controller);
 await context.setOffline(true);
 await page.reload({waitUntil:'domcontentloaded'});
 await page.getByRole('button',{name:'Audio',exact:true}).click();
 await page.getByRole('button',{name:'Saved offline',exact:true}).click();
 await page.waitForFunction(()=>document.querySelectorAll('.audio-row').length===1);
 await page.getByRole('button',{name:'Play Creep',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('#audio').currentTime>0,{},{timeout:15000});
 assert.match(await page.locator('#audio').getAttribute('src'),/^blob:/);
 await page.screenshot({path:'/tmp/sonidos-live-offline.png'});
 assert.deepEqual(errors,[]);
 console.log(JSON.stringify({url:base+'/',videos:published.length,audio:20,css:true,youtubeEmbed:true,realAudioStreamingAndSeek:true,realAudioSavedAcrossOfflineReload:true,mediaSession:true,pageErrors:errors,physicalIPhoneTested:false}));
} finally {await context.close();await browser.close();}
