import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
const base = (process.argv[2] || 'http://127.0.0.1:3011/sonidos-2025/').replace(/\/?$/, '/');
const catalog = JSON.parse(await fs.readFile(new URL('../data.json', import.meta.url), 'utf8'));
catalog.audioReady = true;
catalog.fullAudioReady = true;
catalog.mediaReady = true;
catalog.songs = catalog.songs.slice(0, 2).map((song, i) => ({ ...song, audio: `${base}fixture-${i}.wav` }));
catalog.fullAudio = `${base}fixture-full.wav`;
const samples = 8000 * 8;
const wav = Buffer.alloc(44 + samples * 2);
wav.write('RIFF'); wav.writeUInt32LE(wav.length - 8, 4); wav.write('WAVEfmt ', 8); wav.writeUInt32LE(16, 16); wav.writeUInt16LE(1, 20); wav.writeUInt16LE(1, 22); wav.writeUInt32LE(8000, 24); wav.writeUInt32LE(16000, 28); wav.writeUInt16LE(2, 32); wav.writeUInt16LE(16, 34); wav.write('data', 36); wav.writeUInt32LE(samples * 2, 40);
const browser = await chromium.launch();
try {
 const context = await browser.newContext({ viewport: { width: 390, height: 844 } });
 const page = await context.newPage();
 const errors = [];
 page.on('pageerror', (error) => errors.push(error.message));
 await context.route('**/catalog.js', (route) => route.fulfill({ contentType: 'application/javascript', body: `window.SONIDOS_CATALOG = ${JSON.stringify(catalog)};` }));
 await context.route('**/fixture-*.wav', (route) => route.fulfill({ status: 200, contentType: 'audio/wav', body: wav, headers: { 'Content-Length': String(wav.length), 'Access-Control-Allow-Origin': '*' } }));
 await page.goto(base);
 await page.evaluate(() => navigator.serviceWorker.ready);
 await page.waitForFunction(() => navigator.serviceWorker.controller);
 await page.getByRole('button', { name: 'Audio', exact: true }).click();
 assert.equal(await page.locator('.audio-row').count(), 3);
 await page.getByRole('button', { name: 'Save offline War Pigs', exact: true }).click();
 await page.getByRole('button', { name: 'Remove offline copy of War Pigs', exact: true }).waitFor();
 assert.equal(await page.evaluate(async () => (await (await caches.open('sonidos-audio-masters-v7')).keys()).length), 1);
 await page.getByRole('button', { name: 'Play War Pigs', exact: true }).click();
 await page.waitForFunction(() => document.querySelector('#audio').currentTime > 0);
 assert.match(await page.locator('#audio').getAttribute('src'), /^blob:/);
 assert.equal(await page.evaluate(() => navigator.mediaSession.metadata.title), 'War Pigs');
 await page.screenshot({ path: '/tmp/sonidos-audio-playing-mobile.png' });
 await page.getByRole('button', { name: 'Next song', exact: true }).click();
 await page.waitForFunction(() => document.querySelector('#audio-title').textContent === 'Alive');
 await page.getByRole('button', { name: 'Close audio player', exact: true }).click();
 await context.setOffline(true);
 await page.reload({ waitUntil: 'domcontentloaded' });
 await page.getByRole('button', { name: 'Audio', exact: true }).click();
 await page.getByRole('button', { name: 'Saved offline', exact: true }).click();
 await page.waitForFunction(() => document.querySelectorAll('.audio-row').length === 1);
 await page.getByRole('button', { name: 'Play War Pigs', exact: true }).click();
 await page.waitForFunction(() => document.querySelector('#audio').currentTime > 0);
 assert.match(await page.locator('#audio').getAttribute('src'), /^blob:/);
 await page.getByRole('button', { name: 'Remove offline copy of War Pigs', exact: true }).click();
 await page.getByText('No saved songs.', { exact: true }).waitFor({ state: 'visible' });
 assert.equal(await page.evaluate(async () => (await (await caches.open('sonidos-audio-masters-v7')).keys()).length), 0);
 assert.deepEqual(errors, []);
 await context.close();
 console.log('PASS: save offline, streaming cache, persistent cache across offline reload, local playback, MediaSession, next song, remove offline, no JS errors.');
} finally { await browser.close(); }
